### ISSUE TITLE
remarks upon first try

### ISSUE THREAD

**Issue by pedrobsaila** [hramza/PlayingWithDistributedTracing#1]
Hi @hramza 
I took time to see your distributed tracing demo, here are some remarks :

* I think this line should be ` ./config/prometheus.yml:/etc/prometheus.yml`.
https://github.com/hramza/PlayingWithDistributedTracing/blob/fd72aad6968878f455ee8770931c63a13afea24e/docker-compose.yml#L82
Because when I did docker compose, I got the error :
Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/run/desktop/mnt/host/c/Users/username/Desktop/PlayingWithDistributedTracing/config/prometheus.yml" to rootfs at "/etc/prometheus/prometheus.yml" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

* You could use generics here :
https://github.com/hramza/PlayingWithDistributedTracing/blob/fd72aad6968878f455ee8770931c63a13afea24e/src/SearchEngine.Shared/Infrastructure/Kafka/JsonKafkaSerializer.cs#L15
something like this `return JsonSerializer.Deserialize<T>(data)!;` would work

* The consumer is failing to launch
Unhandled exception. System.Exception: Something goes wrong while creating index !
   at Consumer.Providers.SearchEngineLoader.CreateIndexAsync() in /src/Consumer/Providers/SearchEngineLoader.cs:line 36
   at Program.<Main>$(String[] args) in /src/Consumer/Program.cs:line 47
   at Program.<Main>(String[] args)
when configuring elastic url as http://localhost:9200 it works

* otel container fails to launch 
Error: failed to get config: cannot retrieve the configuration: unable to read the file /etc/otel-collector-config.yaml: read /etc/otel-collector-config.yaml: is a directory
2022/02/15 21:23:34 collector server run finished with error: failed to get config: cannot retrieve the configuration: unable to read the file /etc/otel-collector-config.yaml: read /etc/otel-collector-config.yaml: is a directory

*  👍  For using minimal APIs
*  👍  For using logging with source generators

I'm using docker Docker Desktop 4.4.4 with WSL2

**Comment by hramza** [comment]
Hi @pedrobsaila,

Thank you for your remarks.

I have deleted accidentally prometheus and otel configuration files when pushing the repo. I've restored them.

The consumer is failing to start because elastic takes a while to fire up. I have added `restart: always` so the consumer will restart when an error occurs. I suppose that it will not be the case for production since you should have your elastic cluster configured separately.

It is not due to elastic url : 

<img width="606" alt="Consumer_call_elasticsearch_service" src="https://user-images.githubusercontent.com/10199467/154170959-e90f1496-b658-4457-bdc4-7f8f8c4b547d.png">

Please comment if the issue persists.

Best regards,

**Comment by pedrobsaila** [comment]
Works like a charm now 👍
